-- =====================================================
-- BrainCoach Seed 011
-- Monday Generator MVP public-language correction v1
-- Date: 2026-06-18
-- Target database: bgs_orch
-- Target schema: production
--
-- Purpose:
--   Apply human-review language corrections to Monday generated assets.
--
-- Safety:
--   - Does not alter schema.
--   - Does not update content_units.
--   - Does not approve assets.
--   - Does not schedule or publish anything.
--   - Updates only assets generated by monday_generator_mvp1.
-- =====================================================

BEGIN;

WITH corrected_assets (content_unit_code, asset_text) AS (
    VALUES
    (
        'CUNIT-2026-06-22-IG-REEL-01',
        $$IG REEL / Main phenomenon

Topic:
Мы столько вложили... а что реально осталось?

Hook, first 2 seconds:
Если посчитать последние 3 года, вы довольны отдачей?

Script:
Вы могли вложить в ребенка очень много.

Репетиторы.
Секции.
Английский.
Лагеря.
Сборы.
Время.
Нервы.
Дороги.

И главный вопрос летом не в том, были ли вложения.

Они были.

Вопрос другой:
что из этого сейчас держится без вас?

Если убрать расписание, тренера, репетитора, напоминания и родительский контроль, движение продолжается?

Или оно останавливается?

Вот это и показывает лето.

Не оценки.
Не обещания.
Не планы на сентябрь.

А то, что реально встроилось в ребенка.

CTA:
Напишите в DM одно слово: "вложения".
Разберем, что уже держится само, а что пока держится на внешней поддержке.

Caption:
Мы столько вложили. Что останется к осени?

Visual:
Navigation dashboard. A summer route line with investment checkpoints behind and a question mark near autumn. Use movement line, coordinates, checkpoints, not space or comics.

Production notes:
Calm direct voice. No expert terminology. Parent reality first.$$ 
    ),
    (
        'CUNIT-2026-06-22-IG-STORY-05',
        $$STORY 5 / CTA

Text:
Если хотите, можно коротко написать в DM:

"что вложили"
и
"что хотите сохранить к осени".

Я посмотрю не с позиции оценок.

А с позиции движения:
что уже держится само,
а что пока держится на вас.

CTA:
DM: "вложения"

Visual:
Compact route card with two fields: "вложено" and "должно остаться".

Signal to capture:
DM stories with investments and expected outcomes.$$ 
    ),
    (
        'CUNIT-2026-06-22-THREADS-01',
        $$THREADS / Thought lab

Иногда родители покупают не развитие.

Они покупают надежду, что движение ребенка не сорвется.

Репетитор.
Секция.
Английский.
Лагерь.

Все это может быть полезно.

Но летом становится видно другое:

что ребенок уже может удерживать сам,
а что держалось только потому, что вокруг была внешняя поддержка.

Главный вопрос недели:
что из вложенного должно остаться к осени?

И где сейчас риск, что оно просто исчезнет?

Question:
Что из вложенного для вас важнее всего сохранить?$$
    ),
    (
        'CUNIT-2026-06-22-TG-01',
        $$TELEGRAM / Weekly hub note

Карта недели: инвестиция сделана. Где сейчас движение?

На этой неделе смотрим не на оценки и не на красивые планы.

Смотрим на один вопрос:

что из вложенного уже держится само,
а что держится на внешней поддержке?

Почему это важно летом:

1. В июне уже видно, сохраняется ли темп.
2. Без школы и привычного режима проявляется реальная самостоятельность.
3. Репетитор, тренер или лагерь могут помогать, но не всегда оставляют переносимый результат.
4. Родители часто чувствуют тревогу раньше, чем появляются формальные проблемы.

Главный разговор недели:

Мы столько вложили.
Что останется к осени?

Сегодняшний вопрос:

Если убрать внешнюю поддержку, какая часть прогресса ребенка продолжит держаться?

Ответьте одним сообщением:

"держится само: ..."
"держится на нас: ..."

Эти ответы станут картой сигналов недели.$$
    )
)
UPDATE production.generated_content_assets g
SET
    asset_text = c.asset_text,
    metadata = g.metadata
        || jsonb_build_object(
            'asset_version', 'draft_v1_1',
            'language_correction', 'public_language_v1',
            'language_correction_reason', 'reduce public overuse of trajectory/system wording before Telegram review'
        ),
    updated_at = now()
FROM corrected_assets c
WHERE g.content_unit_code = c.content_unit_code
  AND g.metadata->>'generator' = 'monday_generator_mvp1'
  AND g.metadata->>'content_plan_code' = 'CPLAN-2026-06-22-W01'
  AND g.metadata->>'planned_date' = '2026-06-22';

COMMIT;

-- =====================================================
-- Verification queries:
--
-- SELECT count(*) AS corrected_assets
-- FROM production.generated_content_assets
-- WHERE metadata->>'generator' = 'monday_generator_mvp1'
--   AND metadata->>'content_plan_code' = 'CPLAN-2026-06-22-W01'
--   AND metadata->>'planned_date' = '2026-06-22'
--   AND metadata->>'language_correction' = 'public_language_v1';
--
-- SELECT
--   voice_check_status,
--   approval_status,
--   count(*) AS assets
-- FROM production.generated_content_assets
-- WHERE metadata->>'generator' = 'monday_generator_mvp1'
--   AND metadata->>'content_plan_code' = 'CPLAN-2026-06-22-W01'
--   AND metadata->>'planned_date' = '2026-06-22'
-- GROUP BY voice_check_status, approval_status
-- ORDER BY voice_check_status, approval_status;
--
-- SELECT
--   content_unit_code,
--   left(asset_text, 220) AS preview
-- FROM production.generated_content_assets
-- WHERE metadata->>'generator' = 'monday_generator_mvp1'
--   AND metadata->>'content_plan_code' = 'CPLAN-2026-06-22-W01'
--   AND metadata->>'planned_date' = '2026-06-22'
--   AND content_unit_code IN (
--     'CUNIT-2026-06-22-IG-REEL-01',
--     'CUNIT-2026-06-22-IG-STORY-05',
--     'CUNIT-2026-06-22-THREADS-01',
--     'CUNIT-2026-06-22-TG-01'
--   )
-- ORDER BY content_unit_code;
-- =====================================================
